#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReMinder.Resource", IsApplication=true)]

namespace ReMinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::ReMinder.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int action_bar_background = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int black = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int textColor = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ActionBarLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AnswerListCustomColor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_right = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrow_right_big = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int checkbox_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int checkbox_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int checkmark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chevron = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CreateAccountSelector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int crossmark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int email = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_new = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_overflow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int login_bkg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logo_login = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int OFF = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ON = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int password = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int qna_bkg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int QuestionsCloseButton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int QuestionSingleRowStyle = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int QuestionSingleRowStylePurple = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int QuestionTextView = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int register_bkg = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int reminder_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int SpinnerTextView = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int TransparentButton = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int TransparentButtonPressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int TransparentButtonSelected = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int TransparentToogleVibrationButton = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int user = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int btnClose = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int btnLogin = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int btnNextQuestion = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int btnRegister = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int imgAtionBar = 2131230745;
			
			// aapt resource value: 0x7f080002
			public const int imgCheckmark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int imgLoginLogo = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int listAnswers = 2131230731;
			
			// aapt resource value: 0x7f08001b
			public const int mainMenu = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int overflowMenuItem = 2131230748;
			
			// aapt resource value: 0x7f080016
			public const int spinCategoryOptions = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int spinTimeOptions = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int toggleVibrationOptions = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int txtAnswerEnum = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int txtAnswerText = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int txtEmail = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int txtNewEmail = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int txtNewPassword = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int txtNewUsername = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int txtOptionsAndSettingsHeader = 2131230738;
			
			// aapt resource value: 0x7f080005
			public const int txtPassword = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int txtQuestion = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int txtRepeatPassword = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int txtSubjectsOptions = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int txtTimer = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int txtVibrationOptions = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int txtViewPassword = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int txtViewRegister = 2131230726;
			
			// aapt resource value: 0x7f08001a
			public const int txtViewSpinner = 2131230746;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRowView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Question = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Settings = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int mainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int ApplicationName = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int Close = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Continue = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int CreateAccount = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int EmailHint = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int EmailValidationError = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int ErrorWhileLogin = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ErrorWhileRegistration = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int NotImplemented = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int Password = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int PasswordHint = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int PasswordUnMatchValidationError = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int PasswordValidationError = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int Register = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int RepeatPasswordHint = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int UsernameHint = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int UsernameValidationError = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ReMinder_ActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ReMinderTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
